In [1]:
import glob
from pathlib import Path
import pandas as pd
import polars as pl

import aw
import job_search.jobs as jb
import job_search.config as conf
import job_search.scrape as sc
from job_search.config import P_RAW, P_INTERIM
from job_search.utils import now, reload
from job_search.scrape import DA_SF, DS_SF, DA_HEALTH, HEALTH

_now = now(time=False, days=0)
# _now = '2026-04-20'
P_raw_date = P_RAW / _now.replace('-', '/')
P_interim_date = P_INTERIM / _now.replace('-', '/')

In [2]:
glob_prefix = '../data/interim/2026/**'
health_df = sc.load_json_gz(glob_health := f'{glob_prefix}/{HEALTH}/*.json.gz', metadata=True)
ds_sf_df = sc.load_json_gz(glob_ds_sf := f'{glob_prefix}/{DS_SF}/*.json.gz', metadata=True)
da_health_df = sc.load_json_gz(glob_da_health := f'{glob_prefix}/{DA_HEALTH}/*.json.gz', metadata=True)
da_sf_df = sc.load_json_gz(glob_da_sf := f'{glob_prefix}/{DA_SF}/*.json.gz', metadata=True)

100%|██████████| 172/172 [00:02<00:00, 77.26it/s]
100%|██████████| 270/270 [00:03<00:00, 74.18it/s]

In [ ]:
health_df.shape[0], ds_sf_df.shape[0], da_health_df.shape[0], da_sf_df.shape[0]
# (8809, 8869, 4227, 6683)
# (14221, 17721, 4992, 7452)

(14221, 17721, 4992, 7452)

In [4]:
from markdownify import markdownify as md

def _process_df(jobs_df):
    jobs_df['_url'] = jb.JOB_HTTPS + jobs_df['requisition_id']
    jobs_df['_hash'] = jobs_df['requisition_id']
    jobs_df['_md'] = jobs_df['description']
    jobs_df = (jb.load_jobs(jobs_df)
        .sort_values('estimated_publish_date', ascending=False)
        .dropna(subset='_hash')
        .drop_duplicates(subset='_hash')
        .reset_index(drop=True)
    )#[[*jb.COLS, 'location_latitudes', 'location_longitudes']]
    jobs_df['_md'] = jobs_df['description'].fillna('').map(md)
    return jobs_df

In [6]:
## Takes ~10s
health_parquet_df = _process_df(health_df)
health_parquet_df.to_parquet(f'../data/cache/{HEALTH}.parquet')

In [7]:
## Takes ~10s
ds_sf_parquet_df = _process_df(ds_sf_df)
ds_sf_parquet_df.to_parquet(f'../data/cache/{DS_SF}.parquet')

In [8]:
## Takes ~10s
da_sf_parquet_df = _process_df(da_sf_df)
da_sf_parquet_df.to_parquet(f'../data/cache/{DA_SF}.parquet')

In [9]:
## Takes ~3s
da_health_parquet_df = _process_df(da_health_df)
da_health_parquet_df.to_parquet(f'../data/cache/{DA_HEALTH}.parquet')

In [10]:
all_df = (pd.concat([
    health_df,
    ds_sf_df,
    da_sf_df,
    da_health_df,
]).sort_values(['st_mtime', 'estimated_publish_date'], ascending=True)
    .dropna(subset='requisition_id')
    .drop_duplicates(subset='requisition_id')
    .reset_index(drop=True)
)
# all_df['st_mtime'].mean()
all_df.drop_duplicates(subset='requisition_id')
all_df

,st_mtime,st_size,requisition_id,job_id,board_token,source,apply_url,collapse_key,is_expired,title,...,company_latest_funding_type,company_latest_funding_year,company_latest_funding_amount,company_stock_exchange,company_stock_symbol,location_longitudes,location_latitudes,_url,_hash,_md
0,2026-04-21 01:07:28.288564682,529075,aeuj2gth21hdu1ng,rippling___aitp___d957f484-3943-4dcb-a0f9-72ef...,aitp,rippling,https://ats.rippling.com/aitp/jobs/d957f484-39...,ced7612c2db8707e93b8b32c22d1851175039200bcc225...,False,"Senior AI Engineer, Agentic Systems",...,Seed,2023.0,0.0,None,None,[],[],https://hiring.cafe/job/aeuj2gth21hdu1ng,aeuj2gth21hdu1ng,"<meta><p style=""font-family:""Basel Grotesk"",Ar..."
1,2026-04-21 01:07:28.288564682,529075,min2wb8by0uriqgk,grnhse___axle___4991731007,axle,grnhse,https://job-boards.greenhouse.io/axle/jobs/499...,5181ee3873b269f9cd26f881f54906a928e6145a3866a5...,False,Data Scientist II,...,Grant,2023.0,126000000.0,None,None,[],[],https://hiring.cafe/job/min2wb8by0uriqgk,min2wb8by0uriqgk,"<div style=""font-size: 10pt; font-family: 'Tah..."
2,2026-04-21 01:07:28.288564682,529075,h7vr5u38u76c6cca,workday___salesforce-wd12-external_career_site...,salesforce-wd12-external_career_site,workday,https://salesforce.wd12.myworkdayjobs.com/exte...,baaa53af7f5a95540dff68b9bf6ee996094687172f0126...,False,AI Forward Deployed Engineer (Senior/Lead/Prin...,...,None,NaN,NaN,NYSE,CRM,[-122.175],[47.6205],https://hiring.cafe/job/h7vr5u38u76c6cca,h7vr5u38u76c6cca,"<p style=""text-align:left""><i>To get the best ..."
3,2026-04-21 01:07:28.288564682,529075,xiwbb034q1ili6tb,jobvite___meltwater___ozwfzfwD,meltwater,jobvite,https://jobs.jobvite.com/meltwater/job/ozwfzfw...,b8a27ca174e1de9bec2f65e2c3b2ceb214cff68503ea35...,False,Senior/ Lead Data Solution Engineer,...,Private Equity,2023.0,65000000.0,None,None,[-122.2199],[37.4833],https://hiring.cafe/job/xiwbb034q1ili6tb,xiwbb034q1ili6tb,"Business ApplicationsHybrid Remote,\n\n ..."
4,2026-04-21 01:07:28.288564682,529075,jepny5coqv9pr5m1,ashby___fieldguide___fd1c14ef-a6bb-4cfe-a9fa-2...,fieldguide,ashby,https://jobs.ashbyhq.com/fieldguide/fd1c14ef-a...,fda3fe06d7c06312f3f9ad9af382ca6673c5743c6e2a7f...,False,Lead Data Scientist,...,Series C,2026.0,75000000.0,None,None,[-122.4194],[37.7749],https://hiring.cafe/job/jepny5coqv9pr5m1,jepny5coqv9pr5m1,"<p style=""min-height:1.5em""><strong>About Us:<..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12874,2026-06-05 21:46:38.398396969,160074,999qefv8xxo92isc,workday___wf-wd1-wellsfargojobs___senior-quant...,wf-wd1-wellsfargojobs,workday,https://wf.wd1.myworkdayjobs.com/wellsfargojob...,966eff2a9d8fae3e24bdfcd465a2890860d5f3b2456dc8...,False,Senior Quantitative Analytics Specialist (#001...,...,None,NaN,NaN,NYSE,WFC,[],[],https://hiring.cafe/job/999qefv8xxo92isc,999qefv8xxo92isc,None
12875,2026-06-05 21:46:38.398396969,160074,c53y15l2rwqvcny8,workday___lambweston-wd1-lamb_external___sr-da...,lambweston-wd1-lamb_external,workday,https://lambweston.wd1.myworkdayjobs.com/lamb_...,5257105112a73c6d35d44e9badf5434d789753edcda02d...,False,Sr Data Governance & MDM Specialist,...,None,NaN,NaN,NYSE,LW,[],[],https://hiring.cafe/job/c53y15l2rwqvcny8,c53y15l2rwqvcny8,None
12876,2026-06-05 21:46:38.398396969,160074,b1881nscye4t85ys,smartrecruiters___nbcuniversal3___be3f3d49-05f...,nbcuniversal3,smartrecruiters,https://jobs.smartrecruiters.com/NBCUniversal3...,6e95738bf527e67875fee8bc95b51e6eac5515c02da24c...,False,"Analyst, Digital Inventory",...,None,NaN,NaN,NASDAQ,CMCSA,[],[],https://hiring.cafe/job/b1881nscye4t85ys,b1881nscye4t85ys,None
12877,2026-06-05 21:46:56.002573252,196718,w7s126eifi3jyatq,workday___comscore-wd5-external___lead--client...,comscore-wd5-external,workday,https://comscore.wd5.myworkdayjobs.com/externa...,d97340d9ddee6d2b5ce12aee9bbc408ab1cf2802c0e76d...,False,"Lead, Client Success",...,None,NaN,NaN,NASDAQ,SCOR,[],[],https://hiring.cafe/job/w7s126eifi3jyatq,w7s126eifi3jyatq,None
12878,2026-06-05 21:46:56.002573252,196718,j49iql72uas2nvkc,workday___comscore-wd5-external___associate-da...,comscore-wd5-external,workday,https://comscore.wd5.myworkdayjobs.com/externa...,d97340d9ddee6d2b5ce12aee9bbc408ab1cf2802c0e76d...,False,Associate Data Analyst,...,None,NaN,NaN,NASDAQ,SCOR,[],[],https://hiring.cafe/job/j49iql72uas2nvkc,j49iql72uas2nvkc,None

In [11]:
all_parquet_df = (pd.concat([
        health_parquet_df,
        ds_sf_parquet_df,
        da_sf_parquet_df,
        da_health_parquet_df,
    ]).sort_values('estimated_publish_date', ascending=False)
        .dropna(subset='_hash')
        .drop_duplicates(subset='_hash')
        .reset_index(drop=True)
    )
all_df.to_parquet(f'../data/cache/ALL.parquet')

## Save JSON descriptions

In [ ]:
len([p for p in (jb.P_CACHE / 'json').iterdir()])
# 2402
# 3481

3481

In [15]:
import json

from tqdm import tqdm
import lxml.html

proxy = False
driver = sc.init_driver(proxy=proxy, headless=False)

errors = []
# for _hash in tqdm(all_df[all_df['description'].isna()].sort_values('st_mtime', ascending=False)['requisition_id']):
for _hash in tqdm(all_df.sort_values('st_mtime', ascending=False)['requisition_id']):
    # P_url = jb.P_CACHE / 'json' / f'2xztjhutpo56dvg9.json.gz'
    P_url = jb.P_CACHE / 'url' / f'{_hash}.html'
    P_json = jb.P_CACHE / 'json' / f'{_hash}.json.gz'
    if P_url.exists():
        continue

    # url = jb.VIEW_JOB_HTTPS + _hash
    url = jb.JOB_HTTPS + _hash
    print(url)

    # url_get_content = sc.selenium_get(url, driver=driver)
    try:
        url_get_content = sc.requests_get(url)
    except Exception:
        url_get_content = sc.selenium_get(url, driver=driver)

    root = lxml.html.fromstring(url_get_content)
    _next_data_list = root.xpath("//script[@id='__NEXT_DATA__']")
    if len(_next_data_list) == 0:
        jobs_dict = {}
        errors.append(url)
        print(url)
        continue
    else:
        _next_data = root.xpath("//script[@id='__NEXT_DATA__']")[0]
        jobs_dict = json.loads(_next_data.text_content())
        jobs_dict = jobs_dict.get('props', jobs_dict)

    sc.write_data(P_json, jobs_dict)
    with open(P_url, "w", encoding="utf-8") as f:
        f.write(url_get_content)
    sc.sleep(0.2, 0.5)

  0%|          | 0/12879 [00:00<?, ?it/s]

https://hiring.cafe/job/f4me995wq1kyqt5e
https://hiring.cafe/job/f4me995wq1kyqt5e
https://hiring.cafe/job/xvpkqw1qh27cp5dk
https://hiring.cafe/job/xvpkqw1qh27cp5dk
https://hiring.cafe/job/rgsgsg5songfyc45
https://hiring.cafe/job/rgsgsg5songfyc45
https://hiring.cafe/job/5uuqi289wlfg0nud
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5uuqi289wlfg0nud.json.gz

 31%|███▏      | 4050/12879 [00:00<00:00, 10949.10it/s]

https://hiring.cafe/job/vro5y7l7dwc0x1i5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vro5y7l7dwc0x1i5.json.gz
https://hiring.cafe/job/76m0up8nuhs5lur4

 31%|███▏      | 4050/12879 [00:12<00:00, 10949.10it/s]

Writing: C:\Users\Alex\Dev\job-search\data\cache\json\76m0up8nuhs5lur4.json.gz

 31%|███▏      | 4052/12879 [00:13<00:42, 209.73it/s]

https://hiring.cafe/job/njqx114mwlqbl0xr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\njqx114mwlqbl0xr.json.gz

 31%|███▏      | 4053/12879 [00:15<00:49, 178.88it/s]

https://hiring.cafe/job/4hglon3fj3f8nl2s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4hglon3fj3f8nl2s.json.gz
https://hiring.cafe/job/b5sqr0a9foqmtw1u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b5sqr0a9foqmtw1u.json.gz
https://hiring.cafe/job/iznp4140sdp8r7c0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iznp4140sdp8r7c0.json.gz
https://hiring.cafe/job/pckvvfa9km8z9a34
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pckvvfa9km8z9a34.json.gz
https://hiring.cafe/job/3buxu5elbf6vezmn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3buxu5elbf6vezmn.json.gz
https://hiring.cafe/job/rtokd4p5nq3eglj0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rtokd4p5nq3eglj0.json.gz
https://hiring.cafe/job/4ht5t1j33pf08epc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4ht5t1j33pf08epc.json.gz
https://hiring.cafe/job/3t0gxndgzudn1ilm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3t0gxndgzudn1ilm.json.gz
https://hiring.cafe/job/bfljsgvfq13s9y5t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bfljsgvfq13s9y5t.json.gz
https://hiring.cafe/job/ouqnay7yhfnpucmw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ouqnay7yhfnpucmw.json.gz
https://hiring.cafe/job/5l6h3w5mb45sm6wc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5l6h3w5mb45sm6wc.json.gz
https://hiring.cafe/job/jxi8mno1sicbn9ks

 31%|███▏      | 4053/12879 [00:32<00:49, 178.88it/s]

Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jxi8mno1sicbn9ks.json.gz

 32%|███▏      | 4066/12879 [00:32<02:39, 55.25it/s]

https://hiring.cafe/job/3dp4i78lijqp9dkx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3dp4i78lijqp9dkx.json.gz

 32%|███▏      | 4067/12879 [00:36<03:11, 46.10it/s]

https://hiring.cafe/job/pjwhplg25tzus5dg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pjwhplg25tzus5dg.json.gz
https://hiring.cafe/job/pp2fbnlopmemmr2t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pp2fbnlopmemmr2t.json.gz
https://hiring.cafe/job/9qmsberkz67fbjeq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9qmsberkz67fbjeq.json.gz
https://hiring.cafe/job/ht0jdyperm8ku81l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ht0jdyperm8ku81l.json.gz
https://hiring.cafe/job/bzfyuz6zyjj5tzqg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bzfyuz6zyjj5tzqg.json.gz
https://hiring.cafe/job/plpl8v13vy2bk1mb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\plpl8v13vy2bk1mb.json.gz
https://hiring.cafe/job/1rjx6wkpjfr65a45
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1rjx6wkpjfr65a45.json.gz
https://hiring.cafe/job/r7856dcam1ytcdw0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r7856dcam1ytcdw0.json.gz
https://hiring.cafe/job/wbf5h3w5tz5zly01
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wbf5h3w5tz5zly01.json.gz
https://hiring.cafe/job/hwagvx6ic5fyt6gf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hwagvx6ic5fyt6gf.json.gz

 32%|███▏      | 4077/12879 [00:52<06:31, 22.50it/s]

https://hiring.cafe/job/hqlvp55887by13td
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hqlvp55887by13td.json.gz

 32%|███▏      | 4078/12879 [00:54<06:56, 21.12it/s]

https://hiring.cafe/job/6p1w0k5ktvhiz40s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6p1w0k5ktvhiz40s.json.gz
https://hiring.cafe/job/tw8qboxjhejuvo64
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tw8qboxjhejuvo64.json.gz
https://hiring.cafe/job/i30hwqte7btao26n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i30hwqte7btao26n.json.gz
https://hiring.cafe/job/esdlj7g8ertmo5kl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\esdlj7g8ertmo5kl.json.gz
https://hiring.cafe/job/26t0c9u0embmzcch
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\26t0c9u0embmzcch.json.gz
https://hiring.cafe/job/vfbo0t2b7476b181
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vfbo0t2b7476b181.json.gz
https://hiring.cafe/job/465o0q01djymflv8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\465o0q01djymflv8.json.gz
https://hiring.cafe/job/llbj1w5hh8us399t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\llbj1w5hh8us399t.json.gz
https://hiring.cafe/job/dw6lc6loy4yn5tdw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dw6lc6loy4yn5tdw.json.gz
https://hiring.cafe/job/643sksx4ox4kj907
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\643sksx4ox4kj907.json.gz
https://hiring.cafe/job/nt0xc6x0z7763xjm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nt0xc6x0z7763xjm.json.gz
https://hiring.cafe/job/2wgc783unr7dw5pr

 32%|███▏      | 4078/12879 [01:12<06:56, 21.12it/s]

Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2wgc783unr7dw5pr.json.gz

 32%|███▏      | 4090/12879 [01:12<14:28, 10.12it/s]

https://hiring.cafe/job/7xiclob9lc4cphwp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7xiclob9lc4cphwp.json.gz

 32%|███▏      | 4091/12879 [01:14<15:15,  9.60it/s]

https://hiring.cafe/job/w88xh1gqt5q8tpsq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w88xh1gqt5q8tpsq.json.gz
https://hiring.cafe/job/uofn74jk1jgk5j3n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uofn74jk1jgk5j3n.json.gz
https://hiring.cafe/job/gpmfgavskonxoo9r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gpmfgavskonxoo9r.json.gz
https://hiring.cafe/job/6g1clmlcj9xr0num
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6g1clmlcj9xr0num.json.gz
https://hiring.cafe/job/4a1qubfv449xn80p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4a1qubfv449xn80p.json.gz
https://hiring.cafe/job/3jua8zf64qa2sqbg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3jua8zf64qa2sqbg.json.gz
https://hiring.cafe/job/8ggn97jt05rhpgdz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8ggn97jt05rhpgdz.json.gz
https://hiring.cafe/job/so674wwhbq9k3huu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\so674wwhbq9k3huu.json.gz
https://hiring.cafe/job/726evew6289pw3lt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\726evew6289pw3lt.json.gz
https://hiring.cafe/job/dulb8cb1iaolzuy0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dulb8cb1iaolzuy0.json.gz
https://hiring.cafe/job/iku05c5lrmam0sj4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iku05c5lrmam0sj4.json.gz
https://hiring.cafe/job/lef12w7hg0p5saji
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lef12w7hg0p5saji.json.gz
https://hiring.cafe/job/fe472d3moea5ukpr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fe472d3moea5ukpr.json.gz
https://hiring.cafe/job/rty4ictn2nw3irwl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rty4ictn2nw3irwl.json.gz

 32%|███▏      | 4105/12879 [01:32<28:19,  5.16it/s]

https://hiring.cafe/job/e3c6qoe8m5ybw423
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e3c6qoe8m5ybw423.json.gz

 32%|███▏      | 4106/12879 [01:34<29:37,  4.94it/s]

https://hiring.cafe/job/wqj2rme7plfzli4a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wqj2rme7plfzli4a.json.gz
https://hiring.cafe/job/0gy6hifs14vu66yl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0gy6hifs14vu66yl.json.gz
https://hiring.cafe/job/1xatlowh0qulxgre
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1xatlowh0qulxgre.json.gz
https://hiring.cafe/job/kjn6qzlnn8pk9ek2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kjn6qzlnn8pk9ek2.json.gz
https://hiring.cafe/job/1mvp1xqqlimrd652
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1mvp1xqqlimrd652.json.gz
https://hiring.cafe/job/wsq9wyv6c67lavb8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wsq9wyv6c67lavb8.json.gz
https://hiring.cafe/job/3m2dhn3eme8xke9h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3m2dhn3eme8xke9h.json.gz
https://hiring.cafe/job/hxc7d85kzbhirclv

 32%|███▏      | 4106/12879 [01:52<29:37,  4.94it/s]

Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hxc7d85kzbhirclv.json.gz

 32%|███▏      | 4114/12879 [01:56<59:02,  2.47it/s]

https://hiring.cafe/job/k4h4b54m653jh96g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k4h4b54m653jh96g.json.gz

 32%|███▏      | 4115/12879 [01:58<1:03:06,  2.31it/s]

https://hiring.cafe/job/pibnwdgh9qyr91el
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pibnwdgh9qyr91el.json.gz
https://hiring.cafe/job/gweibp0xg9qqxym9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gweibp0xg9qqxym9.json.gz
https://hiring.cafe/job/jemcbv1ciucpm291
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jemcbv1ciucpm291.json.gz
https://hiring.cafe/job/tnxcd916ogbe1qog
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tnxcd916ogbe1qog.json.gz
https://hiring.cafe/job/x2kr6u4kh3h3zghb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x2kr6u4kh3h3zghb.json.gz
https://hiring.cafe/job/46nm9v6z4hea17xu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\46nm9v6z4hea17xu.json.gz
https://hiring.cafe/job/bihqu4d5uij68e6d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bihqu4d5uij68e6d.json.gz
https://hiring.cafe/job/q1aohbk3ilmdvep2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q1aohbk3ilmdvep2.json.gz
https://hiring.cafe/job/8g61421y9pzoxkkf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8g61421y9pzoxkkf.json.gz
https://hiring.cafe/job/wnbz7buxg6npukro

 32%|███▏      | 4115/12879 [02:12<1:03:06,  2.31it/s]

Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wnbz7buxg6npukro.json.gz

 32%|███▏      | 4125/12879 [02:13<1:28:06,  1.66it/s]

https://hiring.cafe/job/6qtegpg4g941dkzb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6qtegpg4g941dkzb.json.gz

 32%|███▏      | 4126/12879 [02:14<1:30:11,  1.62it/s]

https://hiring.cafe/job/clj76rfpecyiuz2y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\clj76rfpecyiuz2y.json.gz
https://hiring.cafe/job/dffz0umhltrsbbdk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dffz0umhltrsbbdk.json.gz
https://hiring.cafe/job/ujbpty5uil9n7m8v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ujbpty5uil9n7m8v.json.gz
https://hiring.cafe/job/dvvbfptbd2gwrk9n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dvvbfptbd2gwrk9n.json.gz
https://hiring.cafe/job/2v1fgymua55as2n1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2v1fgymua55as2n1.json.gz
https://hiring.cafe/job/mrt45dybmxmnlnn8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mrt45dybmxmnlnn8.json.gz
https://hiring.cafe/job/9qvn5xkcu5hrb73e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9qvn5xkcu5hrb73e.json.gz
https://hiring.cafe/job/tstu29gon5feasoi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tstu29gon5feasoi.json.gz
https://hiring.cafe/job/28s0l1k8k7lmuz3j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\28s0l1k8k7lmuz3j.json.gz
https://hiring.cafe/job/woiuveroti6xlxz1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\woiuveroti6xlxz1.json.gz
https://hiring.cafe/job/kzmal0cxd4fx16c5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kzmal0cxd4fx16c5.json.gz
https://hiring.cafe/job/muhxn4zpoxgvg2l4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\muhxn4zpoxgvg2l4.json.gz
https://hiring.cafe/job/q8v0ey43sdagmuh3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q8v0ey43sdagmuh3.json.gz
https://hiring.cafe/job/wx5i8c386ipiphqe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wx5i8c386ipiphqe.json.gz

 32%|███▏      | 4140/12879 [02:32<2:01:33,  1.20it/s]

https://hiring.cafe/job/x94ocagmja9zjrvn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x94ocagmja9zjrvn.json.gz

 32%|███▏      | 4141/12879 [02:34<2:04:16,  1.17it/s]

https://hiring.cafe/job/ys4unaboxqurubo8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ys4unaboxqurubo8.json.gz
https://hiring.cafe/job/l5z6f9edsqsbo6mp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l5z6f9edsqsbo6mp.json.gz
https://hiring.cafe/job/ig2k0f51ghqgf7kq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ig2k0f51ghqgf7kq.json.gz
https://hiring.cafe/job/dz9q05akl1f40pyn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dz9q05akl1f40pyn.json.gz
https://hiring.cafe/job/ho96diosz4qmvloz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ho96diosz4qmvloz.json.gz
https://hiring.cafe/job/yafk1bvhabdyxbpv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yafk1bvhabdyxbpv.json.gz
https://hiring.cafe/job/rir617mi126y3o52
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rir617mi126y3o52.json.gz
https://hiring.cafe/job/o8gq31303cs6yp9i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o8gq31303cs6yp9i.json.gz
https://hiring.cafe/job/l7tquox9mwsmy01r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l7tquox9mwsmy01r.json.gz
https://hiring.cafe/job/5xcyi4osbnnchfoo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5xcyi4osbnnchfoo.json.gz
https://hiring.cafe/job/bytkqt055gxsw1lz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bytkqt055gxsw1lz.json.gz
https://hiring.cafe/job/8wwcx3kpj2v3fx3h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8wwcx3kpj2v3fx3h.json.gz
https://hiring.cafe/job/r8uaxtht8ms1a586
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r8uaxtht8ms1a586.json.gz
https://hiring.cafe/job/pu92zyck7kh8m9qj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pu92zyck7kh8m9qj.json.gz
https://hiring.cafe/job/ftwjyolbu8xtwh1p

 32%|███▏      | 4141/12879 [02:52<2:04:16,  1.17it/s]

Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ftwjyolbu8xtwh1p.json.gz

 32%|███▏      | 4156/12879 [02:53<2:28:19,  1.02s/it]

https://hiring.cafe/job/n7514nxtkfefc1e9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n7514nxtkfefc1e9.json.gz

 32%|███▏      | 4157/12879 [02:54<2:29:40,  1.03s/it]

https://hiring.cafe/job/s3pkulmnbnaojhyx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s3pkulmnbnaojhyx.json.gz
https://hiring.cafe/job/wsniam5htrb89g86
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wsniam5htrb89g86.json.gz
https://hiring.cafe/job/tli6dt4lgsv4sdg0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tli6dt4lgsv4sdg0.json.gz
https://hiring.cafe/job/ijtees66qijuhusf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ijtees66qijuhusf.json.gz
https://hiring.cafe/job/earbw5h4r7c9zhml
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\earbw5h4r7c9zhml.json.gz
https://hiring.cafe/job/opw6rrshlg7l4403

 32%|███▏      | 4162/12879 [03:01<06:19, 22.95it/s]

KeyboardInterrupt:

In [371]:
url = 'https://hiring.cafe/job/2xztjhutpo56dvg9'

In [382]:
import json
import lxml.html

url_get_content = sc.requests_get(url)
root = lxml.html.fromstring(url_get_content)
_next_data_list = root.xpath("//script[@id='__NEXT_DATA__']")
if len(_next_data_list) == 0:
    jobs_dict = {}
else:
    _next_data = root.xpath("//script[@id='__NEXT_DATA__']")[0]
    jobs_dict = json.loads(_next_data.text_content())
    jobs_dict = jobs_dict.get('props', jobs_dict)

In [395]:
(P_json := jb.P_CACHE / 'json' / '2xztjhutpo56dvg9.json.gz').exists()

False

In [ ]:
## Takes ~35s
glob_str = '../data/cache/json/*.json.gz'
json_gz_paths = sorted([Path(path) for path in glob.glob(glob_str, recursive=True)])
# pl_df = pl.read_ndjson(json_gz_paths)
json_gz_list = []
for P_json_gz in tqdm(json_gz_paths):
    _json_gz_df = pd.read_json(P_json_gz, lines=True, compression='gzip')
    json_gz_list.append(_json_gz_df)
pl_df = pd.concat(json_gz_list)
_pageProps = pl_df['pageProps']

100%|██████████| 3114/3114 [00:21<00:00, 143.45it/s]

In [24]:
json_gz_df = pd.DataFrame({
    'hits': _pageProps,
})
json_gz_df['st_mtime'] = pd.to_datetime([p.stat().st_mtime for p in json_gz_paths], unit='s')
json_gz_df['st_size'] = [p.stat().st_size for p in json_gz_paths]
json_gz_df = json_gz_df[json_gz_df['hits'].str.len() == 1].reset_index(drop=True)

In [26]:
df = json_gz_df#.explode('hits')
job = df['hits'].str['job']
job_info = job.str['job_information']
v5_processed = job.str['v5_processed_job_data']
v5_company_data = job.str['v5_processed_company_data'].apply(lambda x: x if isinstance(x, dict) else {})
company_data = job.str['enriched_company_data']

df['requisition_id'] = job.str['requisition_id']
df['job_id'] = job.str['id']
df['board_token'] = job.str['board_token'].astype(str)
df['source'] = job.str['source']
df['apply_url'] = job.str['apply_url']
df['collapse_key'] = job.str['collapse_key']
df['is_expired'] = job.str['is_expired']

# Job information
df['title'] = job_info.str['title']
df['job_title_raw'] = job_info.str['job_title_raw']
df['description'] = job_info.str['description']
df['core_job_title'] = v5_processed.str['core_job_title']
df['requirements_summary'] = v5_processed.str['requirements_summary']

# Structured data
df['technical_tools'] = v5_processed.str['technical_tools']
df['licenses_certifications'] = v5_processed.str['licenses_or_certifications']
df['role_activities'] = v5_processed.str['role_activities']
df['language_requirements'] = v5_processed.str['language_requirements']

# Degree requirements
df['associates_degree_requirement'] = v5_processed.str['associates_degree_requirement']
df['associates_degree_fields'] = v5_processed.str['associates_degree_fields_of_study']
df['bachelors_degree_requirement'] = v5_processed.str['bachelors_degree_requirement']
df['bachelors_degree_fields'] = v5_processed.str['bachelors_degree_fields_of_study']
df['masters_degree_requirement'] = v5_processed.str['masters_degree_requirement']
df['masters_degree_fields'] = v5_processed.str['masters_degree_fields_of_study']
df['doctorate_degree_requirement'] = v5_processed.str['doctorate_degree_requirement']
df['doctorate_degree_fields'] = v5_processed.str['doctorate_degree_fields_of_study']
df['is_high_school_required'] = v5_processed.str['is_high_school_required']

# Experience requirements
df['min_industry_role_yoe'] = v5_processed.str['min_industry_and_role_yoe']
df['is_min_industry_role_yoe_not_mentioned'] = v5_processed.str['is_min_industry_and_role_yoe_not_mentioned']
df['min_management_leadership_yoe'] = v5_processed.str['min_management_and_leadership_yoe']
df['is_min_management_leadership_yoe_not_mentioned'] = v5_processed.str['is_min_management_and_leadership_yoe_not_mentioned']

# Role details
df['job_category'] = v5_processed.str['job_category']
df['commitment'] = v5_processed.str['commitment']
df['role_type'] = v5_processed.str['role_type']
df['seniority_level'] = v5_processed.str['seniority_level']

# Workplace
df['workplace_type'] = v5_processed.str['workplace_type']
df['workplace_physical_environment'] = v5_processed.str['workplace_physical_environment']
df['formatted_workplace_location'] = v5_processed.str['formatted_workplace_location']
df['is_workplace_worldwide_ok'] = v5_processed.str['is_workplace_worldwide_ok']
df['workplace_cities'] = v5_processed.str['workplace_cities']
df['workplace_counties'] = v5_processed.str['workplace_counties']
df['workplace_states'] = v5_processed.str['workplace_states']
df['workplace_countries'] = v5_processed.str['workplace_countries']
df['workplace_continents'] = v5_processed.str['workplace_continents']
df['boundless_workplace_states'] = v5_processed.str['boundless_workplace_states']
df['boundless_workplace_countries'] = v5_processed.str['boundless_workplace_countries']
df['boundless_workplace_continents'] = v5_processed.str['boundless_workplace_continents']
df['number_of_workplace_cities'] = v5_processed.str['number_of_workplace_cities']
df['number_of_workplace_counties'] = v5_processed.str['number_of_workplace_counties']
df['number_of_workplace_states'] = v5_processed.str['number_of_workplace_states']
df['number_of_workplace_countries'] = v5_processed.str['number_of_workplace_countries']
df['number_of_workplace_continents'] = v5_processed.str['number_of_workplace_continents']

# Work conditions
df['oral_communication_level'] = v5_processed.str['oral_communication_level']
df['physical_labor_intensity'] = v5_processed.str['physical_labor_intensity']
df['physical_position'] = v5_processed.str['physical_position']
df['computer_usage'] = v5_processed.str['computer_usage']
df['cognitive_demand'] = v5_processed.str['cognitive_demand']
df['air_travel_requirement'] = v5_processed.str['air_travel_requirement']
df['land_travel_requirement'] = v5_processed.str['land_travel_requirement']
df['morning_shift_work'] = v5_processed.str['morning_shift_work']
df['evening_shift_work'] = v5_processed.str['evening_shift_work']
df['overnight_work'] = v5_processed.str['overnight_work']
df['on_call_requirement'] = v5_processed.str['on_call_requirement']
df['weekend_availability_required'] = v5_processed.str['weekend_availability_required']
df['holiday_availability_required'] = v5_processed.str['holiday_availability_required']
df['overtime_required'] = v5_processed.str['overtime_required']

# Compensation
df['yearly_min_compensation'] = v5_processed.str['yearly_min_compensation']
df['yearly_max_compensation'] = v5_processed.str['yearly_max_compensation']
df['monthly_min_compensation'] = v5_processed.str['monthly_min_compensation']
df['monthly_max_compensation'] = v5_processed.str['monthly_max_compensation']
df['weekly_min_compensation'] = v5_processed.str['weekly_min_compensation']
df['weekly_max_compensation'] = v5_processed.str['weekly_max_compensation']
df['hourly_min_compensation'] = v5_processed.str['hourly_min_compensation']
df['hourly_max_compensation'] = v5_processed.str['hourly_max_compensation']
df['biweekly_min_compensation'] = v5_processed.str['bi-weekly_min_compensation']
df['biweekly_max_compensation'] = v5_processed.str['bi-weekly_max_compensation']
df['daily_min_compensation'] = v5_processed.str['daily_min_compensation']
df['daily_max_compensation'] = v5_processed.str['daily_max_compensation']
df['is_compensation_transparent'] = v5_processed.str['is_compensation_transparent']
df['listed_compensation_currency'] = v5_processed.str['listed_compensation_currency']
df['listed_compensation_frequency'] = v5_processed.str['listed_compensation_frequency']

# Benefits
df['four_oh_one_k_matching'] = v5_processed.str['401k_matching']
df['generous_paid_time_off'] = v5_processed.str['generous_paid_time_off']
df['four_day_work_week'] = v5_processed.str['four_day_work_week']
df['tuition_reimbursement'] = v5_processed.str['tuition_reimbursement']
df['retirement_plan'] = v5_processed.str['retirement_plan']
df['generous_parental_leave'] = v5_processed.str['generous_parental_leave']
df['fair_chance'] = v5_processed.str['fair_chance']
df['visa_sponsorship'] = v5_processed.str['visa_sponsorship']
df['relocation_assistance'] = v5_processed.str['relocation_assistance']
df['military_veterans'] = v5_processed.str['military_veterans']

# Other
df['security_clearance'] = v5_processed.str['security_clearance']
df['is_driver_license_required'] = v5_processed.str['is_driver_license_required']
df['position_employer_type'] = v5_processed.str['position_employer_type']
df['company_sector_and_industry'] = v5_processed.str['company_sector_and_industry']

# Dates
_estimated_publish_date = v5_processed.str['estimated_publish_date']
# if isinstance(_estimated_publish_date, int):
#     _estimated_publish_date = datetime.fromtimestamp(_estimated_publish_date / 1000)
df['estimated_publish_date'] = _estimated_publish_date
df['estimated_publish_date_millis'] = v5_processed.str['estimated_publish_date_millis']

_v5_is_public = v5_company_data.str['is_public']
# _v5_org_type = {True: 'Public', False: 'Private'}.get(_v5_is_public)
# if v5_company_data.get('is_non_profit'):
#     _v5_org_type = 'Non-Profit'
_v5_org_type = _v5_is_public.map({True: 'Public', False: 'Private'})
_v5_org_type.loc[v5_company_data.str['is_non_profit'].astype(bool)] = 'Non-Profit'

df = pd.concat([df,
    # User interactions
    job_info.str['hiddenFromUsers'].rename('hiddenFromUsers'),
    job_info.str['viewedByUsers'].rename('viewedByUsers'),
    job_info.str['applied_from_users'].rename('applied_from_users'),

    # Enriched Company data (embedded)
    company_data.str['enriched_at'].rename('company_enriched_at'),
    company_data.str['status'].rename('company_status'),
    company_data.str['name'].fillna(v5_processed.str['company_name']).fillna(v5_company_data.str['name']).rename('company_name'),
    company_data.str['homepage_uri'].fillna(v5_processed.str['company_website']).fillna(v5_company_data.str['website']).rename('company_homepage_uri'),
    company_data.str['hq_country'].fillna(v5_company_data.str['headquarters_country']).rename('company_hq_country'),
    company_data.str['parent_company'].fillna(v5_company_data.str['parent_company']).rename('company_parent_company'),
    company_data.str['subsidiaries'].fillna(v5_company_data.str['subsidiaries']).rename('company_subsidiaries'),
    company_data.str['industries'].fillna(v5_company_data.str['industries']).rename('company_industries'),
    company_data.str['activities'].fillna(v5_processed.str['company_activities']).fillna(v5_company_data.str['activities']).apply(lambda x: x if isinstance(x, list) else []).rename('company_activities'),
    company_data.str['nb_employees'].fillna(v5_company_data.str['number_employees'].astype(float)).rename('company_nb_employees'),
    company_data.str['year_founded'].fillna(v5_company_data.str['year_founded'].astype(float)).rename('company_year_founded'),
    company_data.str['tagline'].fillna(v5_processed.str['tagline']).fillna(v5_company_data.str['tagline']).rename('company_tagline'),
    company_data.str['organization_type'].fillna(_v5_org_type).rename('company_organization_type'),
    company_data.str['latest_funding_investors'].fillna(v5_company_data.str['investors']).rename('company_latest_funding_investors)'),
    company_data.str['latest_funding_type'].fillna(v5_company_data.str['latest_funding_series']).rename('company_latest_funding_type'),
    company_data.str['latest_funding_year'].fillna(v5_company_data.str['latest_funding_year'].astype(float)).rename('company_latest_funding_year'),
    company_data.str['latest_funding_amount'].fillna(v5_company_data.str['latest_funding_amount'].astype(float)).rename('company_latest_funding_amount'),
    company_data.str['stock_exchange'].fillna(v5_company_data.str['stock_exchange']).rename('company_stock_exchange'),
    company_data.str['stock_symbol'].fillna(v5_company_data.str['stock_exchange']).rename('company_stock_symbol'),

    # Extract location arrays
    job.str['_geoloc'].apply(lambda x: x if isinstance(x, list) else []).apply(lambda x_list: [x.get('lon') for x in x_list] if not isinstance(x_list, float) else []).rename('location_longitudes'),
    job.str['_geoloc'].apply(lambda x: x if isinstance(x, list) else []).apply(lambda x_list: [x.get('lat') for x in x_list] if not isinstance(x_list, float) else []).rename('location_latitudes'),
], axis=1).drop(columns='hits').reset_index(drop=True)

In [27]:
hash_set = set(df['requisition_id'])

In [28]:
x_df = df.sort_values(['estimated_publish_date', 'requisition_id']).reset_index(drop=True).drop(columns=['st_mtime', 'st_size', 'is_expired'])
y_df = all_df.query('requisition_id in @hash_set').sort_values(['estimated_publish_date', 'requisition_id']).reset_index(drop=True).drop(columns=['st_mtime', 'st_size', 'is_expired'])

In [29]:
x_df.shape, y_df.shape

((3109, 118), (3109, 121))

In [30]:
x_df.columns[:1]

Index(['requisition_id'], dtype='object')

In [31]:
# x_df[x_df.columns[118:]].equals(y_df[x_df.columns[118:]])

# x_df[x_df.columns[:9]].equals(y_df[x_df.columns[:9]])
x_df[x_df.columns[118:]].equals(y_df[x_df.columns[118:]])

True

In [32]:
eq_list = []
neq_list = []
for col in x_df.columns:
    if x_df[col].equals(y_df[col]):
        eq_list.append(col)
    else:
        neq_list.append(col)
eq_list = pd.Series(eq_list)
neq_list = pd.Series(neq_list)

In [33]:
len(eq_list), len(neq_list)

(58, 60)

In [34]:
x_df['hiddenFromUsers'] = x_df['hiddenFromUsers'].apply(lambda x: x if isinstance(x, list) else [])
y_df['hiddenFromUsers'] = y_df['hiddenFromUsers'].apply(lambda x: x if isinstance(x, list) else [])

In [35]:
nperc_list = []
for ncol in neq_list:
    if isinstance(x_df[ncol].iloc[0], list):
        nperc_list.append(sum(x_df[ncol].str.len() == y_df[ncol].str.len()))
    # elif isinstance(x_df[ncol].iloc[0], dict):
    #     nperc_list.append(sum(x_df[ncol].str.len() == y_df[ncol].str.len()))
    else:
        nperc_list.append(perc := sum(x_df[ncol] == y_df[ncol]))
    print(f'{ncol}: {perc/len(x_df):.2f}')

description: 0.00
technical_tools: 0.00
licenses_certifications: 0.00
role_activities: 0.00
language_requirements: 0.00
associates_degree_fields: 0.00
bachelors_degree_fields: 0.00
masters_degree_fields: 0.00
doctorate_degree_fields: 0.00
is_high_school_required: 1.00
is_min_management_leadership_yoe_not_mentioned: 1.00
commitment: 1.00
is_workplace_worldwide_ok: 1.00
workplace_cities: 1.00
workplace_counties: 1.00
workplace_states: 1.00
workplace_countries: 1.00
workplace_continents: 1.00
boundless_workplace_states: 1.00
boundless_workplace_countries: 1.00
boundless_workplace_continents: 1.00
number_of_workplace_cities: 1.00
number_of_workplace_counties: 1.00
number_of_workplace_states: 1.00
number_of_workplace_countries: 1.00
number_of_workplace_continents: 1.00
weekend_availability_required: 1.00
holiday_availability_required: 1.00
overtime_required: 1.00
monthly_min_compensation: 0.91
monthly_max_compensation: 0.91
weekly_min_compensation: 0.91
weekly_max_compensation: 0.91
hourly_min_compensation: 0.91
hourly_max_compensation: 0.91
biweekly_min_compensation: 0.91
biweekly_max_compensation: 0.91
daily_min_compensation: 0.91
daily_max_compensation: 0.91
is_compensation_transparent: 1.00
four_oh_one_k_matching: 1.00
generous_paid_time_off: 1.00
four_day_work_week: 1.00
tuition_reimbursement: 1.00
retirement_plan: 1.00
generous_parental_leave: 1.00
fair_chance: 1.00
visa_sponsorship: 1.00
relocation_assistance: 1.00
military_veterans: 1.00
is_driver_license_required: 1.00
estimated_publish_date_millis: 1.00
hiddenFromUsers: 1.00
viewedByUsers: 1.00
company_subsidiaries: 1.00
company_industries: 1.00
company_activities: 1.00
company_latest_funding_investors): 1.00
location_longitudes: 1.00
location_latitudes: 1.00

In [36]:
df_all = pd.concat([
    df,
    all_df.query('requisition_id not in @hash_set')
]).sort_values(['estimated_publish_date', 'requisition_id'], ascending=[False, True], ignore_index=True)
df_all

,st_mtime,st_size,requisition_id,job_id,board_token,source,apply_url,collapse_key,is_expired,title,...,company_latest_funding_type,company_latest_funding_year,company_latest_funding_amount,company_stock_exchange,company_stock_symbol,location_longitudes,location_latitudes,_url,_hash,_md
0,2026-06-04 23:50:14.735276222,4106,6t62p1uu48prt1bf,grnhse___weave___4274000009,weave,grnhse,https://job-boards.greenhouse.io/weave/jobs/42...,72495f30e8b417cc46adc426c9ec4cc2a8ba3206674273...,False,Senior AI Engineer,...,Series A,2025.0,2.000000e+07,None,None,[-122.4194],[37.7749],NaN,NaN,NaN
1,2026-06-04 23:47:18.206417322,5292,9u9hz2zrcbe557c5,grnhse___cafortune___5151678007,cafortune,grnhse,https://job-boards.greenhouse.io/cafortune/job...,4ad01afeb6d93eec58cf45449cc453138905a9cecf86be...,False,Senior Category Analyst,...,Corporate Round,2013.0,0.000000e+00,None,None,[-87.6298],[41.8781],NaN,NaN,NaN
2,2026-06-04 23:50:16.016179085,4248,7l6u9slrantdnlos,ashby___turquoise-health___db840fb4-7cf4-4b53-...,turquoise-health,ashby,https://jobs.ashbyhq.com/turquoise-health/db84...,9349c8e0a623b14761b26d2acb8ddf969dae44c68303ba...,False,"Data Science Engineer, Analytics",...,Series C,2026.0,4.000000e+07,None,None,[-117.1611],[32.7157],NaN,NaN,NaN
3,2026-06-04 23:48:31.926485062,4143,987nlzsi1as0amuk,breezy___pyrovio___a0653fb2684d,pyrovio,breezy,https://pyrovio.breezy.hr/p/a0653fb2684d-copil...,bfc344fe7010931c0b1caf788268c676e78945867ce349...,False,Copilot Developer/AI Engineer,...,None,NaN,NaN,None,None,[-81.519],[41.0814],NaN,NaN,NaN
4,2026-06-04 23:48:32.925237656,5762,bsm0p2eb45a8iwm3,grnhse___sonyinteractiveentertainmentglobal___...,sonyinteractiveentertainmentglobal,grnhse,https://job-boards.greenhouse.io/sonyinteracti...,34d49acddb204e381d887ddfce06a363e3abe31e854fc8...,False,"Senior Software Development Engineer In Test, ...",...,None,NaN,NaN,NYSE,SONY,[-122.3255],[37.563],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12659,2026-05-08 22:03:08.651313305,110361,3dp4i78lijqp9dkx,icims___treliantllc___b38ffd47-59cd-46dc-bb8a-...,treliantllc,icims,https://careers-treliant.icims.com/jobs/1803/j...,c4fdab5f4c0db0f98deddc1f7ef85e6e1b012975a7d200...,False,"Consultant, Risk Management",...,Corporate Round,2025.0,NaN,None,None,[],[],https://hiring.cafe/job/3dp4i78lijqp9dkx,3dp4i78lijqp9dkx,"Overview:\n<p style=""margin: 0px;""><span style..."
12660,2026-05-08 22:03:08.651313305,110361,wbf5h3w5tz5zly01,taleo_careersection_s01stantec_230000P8,s01stantec,taleo_careersection,https://s01stantec.taleo.net/careersection/ex1...,cc10f9e7e974fb3278db4d585682047299deea5f615ebb...,False,Utility Economics & Financial Forecasting Analyst,...,None,NaN,NaN,New York Stock Exchange,STN,[],[],https://hiring.cafe/job/wbf5h3w5tz5zly01,wbf5h3w5tz5zly01,<p>Many of the world’s top engineers and scien...
12661,2026-05-08 22:03:08.651313305,110361,jxi8mno1sicbn9ks,icims___bottomline___118a1ead-c768-440f-8563-3...,bottomline,icims,https://careers-bottomline.icims.com/jobs/1471...,9d6296e83f0efd2f29f9367d5e63c75152c905ac230c30...,False,Director of Analytics and Reporting,...,None,NaN,NaN,None,None,[],[],https://hiring.cafe/job/jxi8mno1sicbn9ks,jxi8mno1sicbn9ks,"Overview & Benefits:\n<p style=""margin: 0px;"">..."
12662,2026-05-08 22:03:08.651313305,110361,5l6h3w5mb45sm6wc,breezy___vianai-systems___2709786e7a57,vianai-systems,breezy,https://vianai-systems.breezy.hr/p/2709786e7a5...,6380e5f1d8f422da23a203da1d7a74653ba07a9b256354...,False,Data Scientist,...,Series B,2021.0,1.400000e+08,None,None,[],[],https://hiring.cafe/job/5l6h3w5mb45sm6wc,5l6h3w5mb45sm6wc,<p><strong>The Opportunity:</strong></p> <p>Vi...
12663,2026-04-29 23:52:56.139958620,157032,aluhqzbqmbazyabk,smartrecruiters___walgreens7___09cd9a1a-0fd1-4...,walgreens7,smartrecruiters,https://jobs.smartrecruiters.com/Walgreens7/74...,332f7ff41341e4fed1423da10c5d6bd61d45747f5684d1...,False,"Senior Business Systems Analyst ""Hybrid""",...,Private Equity,2025.0,1.000000e+10,None,None,[-87.8445119],[42.1711365],https://hiring.cafe/job/aluhqzbqmbazyabk,aluhqzbqmbazyabk,<strong>Company Description:</strong><p>Walgre...

In [ ]:
## Takes ~35s
df_all_parquet_df = _process_df(df_all)
df_all_parquet_df.to_parquet(f'../data/cache/df.parquet')

In [47]:
(df_all_parquet_df['_md'] == '').sum()

np.int64(7)

## END